// Generated by scripts/build_constants.mjs. Do not edit by hand.
window.VALIDATION_CONSTANTS = {
  "MAX_WORD_LENGTH": 50,
  "MAX_NAME_LENGTH": 24,
  "ROOM_CODE_LENGTH": 6,
  "VOTE_TOTAL_SECONDS": 300,
  "VOTE_FINAL_SECONDS": 10
};
