import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import validationConstants from "../shared/validationConstants.cjs";

const {
  MAX_WORD_LENGTH,
  MAX_NAME_LENGTH,
  ROOM_CODE_LENGTH,
  VOTE_TOTAL_SECONDS,
  VOTE_FINAL_SECONDS
} = validationConstants;

function parseEnvInt(name, fallback) {
  const raw = process.env[name];
  if (!raw) return fallback;
  const value = Number.parseInt(raw, 10);
  return Number.isFinite(value) ? value : fallback;
}

const voteTotalSeconds = parseEnvInt("VOTE_TOTAL_SECONDS", VOTE_TOTAL_SECONDS);
const voteFinalSeconds = parseEnvInt("VOTE_FINAL_SECONDS", VOTE_FINAL_SECONDS);

const output = `// Generated by scripts/build_constants.mjs. Do not edit by hand.
window.VALIDATION_CONSTANTS = ${JSON.stringify({
  MAX_WORD_LENGTH,
  MAX_NAME_LENGTH,
  ROOM_CODE_LENGTH,
  VOTE_TOTAL_SECONDS: voteTotalSeconds,
  VOTE_FINAL_SECONDS: voteFinalSeconds
}, null, 2)};
`;

writeFileSync(resolve("validationConstants.js"), output, "utf8");
