import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { MAX_WORD_LENGTH, MAX_NAME_LENGTH, ROOM_CODE_LENGTH } from "../shared/validationConstants.mjs";

const output = `// Generated by scripts/build_constants.mjs. Do not edit by hand.
window.VALIDATION_CONSTANTS = ${JSON.stringify({ MAX_WORD_LENGTH, MAX_NAME_LENGTH, ROOM_CODE_LENGTH }, null, 2)};
`;

writeFileSync(resolve("validationConstants.js"), output, "utf8");
